namespace:
  name: demo

service:
  type: ClusterIP
  port: 8111

image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent

replicaCount: 3

resources:
  requests:
    cpu: 50m
    memory: 256Mi

configmap:
  data: "version: alpine"
